version: '3.8'

services:
  app:
    container_name: car
    image: openjdk:17-jdk-slim
    build:
      context: .
      dockerfile: Dockerfile
    environment:
        - SQL_URL=jdbc:postgresql://0.0.0.0:5432/car
    ports:
      - "8080:8080"