version: '3.8'

services:
  app:
    container_name: car
    image: tugjabg/vmcapi:v0.0.1
    restart: always
    networks:
      - "be-network"
#    environment:
#        - SQL_URL=jdbc:postgresql://my_postgres:5432/car
    ports:
      - "8081:8081"
  postgres:
    container_name: my_postgres
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: phuctv142024
      POSTGRES_DB: car
    restart: always
    networks:
      - "be-network"
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
    postgres:
