# Spring Boot configuration
spring:
  profiles:
    active: development
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/car
    username: admin
    password: phuctv142024
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    open-in-view: false
#    generate-ddl: true
# Logger configuration
#logging:
#  pattern:
#    console: "%d %-5level %logger : %msg%n"
#  level:
#    org.springframework: info
#    org.hibernate: debug
server:
  compression:
    enabled: true
  port: 8080
  servlet:
    context-path: /api

app:
  s3:
    accessKey: AKIA3FLD37MOECUTY6EK
    secretKey: 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
  security:
    jwtSecret: vyfmojpjkagyulhyjhcutvibxvhhknadrscrpjpxjgeqyfxcuhirkczgsqxigeda
    jwtExpirationInMs: 5400000