# Spring Boot configuration
spring:
  profiles:
    active: development
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://18.140.157.75:5432/test
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    open-in-view: false
#    generate-ddl: true
# Logger configuration
#logging:
#  pattern:
#    console: "%d %-5level %logger : %msg%n"
#  level:
#    org.springframework: info
#    org.hibernate: debug
server:
  port: 8080

app:
  auth:
    jwtSecret: abcyxz
    jwtExpirationMs: 5400000
  s3:
    url: http://localhost:9000
    bucket: vmc
    accessKey: admin
    secretKey: admin
